// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

 

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"
 

// Constraints:

// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lowercase English letters

public class Solution {
    public static void Main(String[] args) {
       String s = "abcdef";
       String t = "abcedfg";
       Console.WriteLine(differenceInChar(s,t));
    }
    static char differenceInChar(String s, String t)
    {
        int result = t[s.Length];
        for(int i = 0; i < s.Length; i++)
        {
            result = result ^ s[i] ^ t[i];
        }
    return (char)result;
    }

}